/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package QuanLyGUI;

import org.jfree.layout.LCBLayout;

/**
 *
 * @author Win 10
 */
public class CalamPanel_1 extends javax.swing.JPanel {

    /**
     * Creates new form CalamPanel
     */
    public CalamPanel_1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btnCaLam1 = new javax.swing.JButton();
        btnPhanCong1 = new javax.swing.JButton();
        lbMaca1 = new javax.swing.JLabel();
        txtMaca1 = new javax.swing.JTextField();
        lbGioKetThu = new javax.swing.JLabel();
        txtMaca2 = new javax.swing.JTextField();
        tbCalam = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        cbCalam = new javax.swing.JComboBox<>();
        lbThu = new javax.swing.JLabel();
        cbThu = new javax.swing.JComboBox<>();
        lbNgayBatDau = new javax.swing.JLabel();
        lbThu2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        jButton1.setText("jButton1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setAutoscrolls(true);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLayout(null);

        btnCaLam1.setText("Danh sách ca làm");
        btnCaLam1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCaLam1ActionPerformed(evt);
            }
        });
        add(btnCaLam1);
        btnCaLam1.setBounds(20, 300, 161, 51);

        btnPhanCong1.setText("Danh sách phân công");
        btnPhanCong1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPhanCong1ActionPerformed(evt);
            }
        });
        add(btnPhanCong1);
        btnPhanCong1.setBounds(20, 380, 161, 51);

        lbMaca1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbMaca1.setText("Mã ca");
        add(lbMaca1);
        lbMaca1.setBounds(180, 120, 67, 42);
        add(txtMaca1);
        txtMaca1.setBounds(320, 180, 143, 20);

        lbGioKetThu.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbGioKetThu.setText("Ngày kết thúc");
        add(lbGioKetThu);
        lbGioKetThu.setBounds(560, 170, 110, 42);
        add(txtMaca2);
        txtMaca2.setBounds(690, 180, 140, 20);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"HC1S", "3/12/2020", "10/12/2020", "NV1", ""},
                {"HC1C", "3/11/2020", "10/11/2020", "NV2", null},
                {"", "", null, null, null},
                {"", "", null, null, null},
                {"", "", null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã ca", "Ngày bắt đầu", "Ngày kết thúc", "Mã nhân viên", "Ghi chú"
            }
        ));
        tbCalam.setViewportView(jTable1);

        add(tbCalam);
        tbCalam.setBounds(247, 373, 693, 232);

        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });
        add(btnThem);
        btnThem.setBounds(320, 300, 122, 49);

        btnSua.setText("Sửa");
        add(btnSua);
        btnSua.setBounds(530, 300, 122, 49);

        btnXoa.setText("Xóa");
        add(btnXoa);
        btnXoa.setBounds(740, 300, 123, 49);

        cbCalam.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "HC1S", "HC1S", "NV1", "NV2", "NV3" }));
        cbCalam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCalamActionPerformed(evt);
            }
        });
        add(cbCalam);
        cbCalam.setBounds(320, 130, 143, 20);

        lbThu.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbThu.setText("Ghi chú");
        add(lbThu);
        lbThu.setBounds(180, 220, 70, 42);

        cbThu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NV1", "NV2", "NV3", "NV4" }));
        cbThu.setLightWeightPopupEnabled(false);
        cbThu.setOpaque(false);
        cbThu.setPreferredSize(new java.awt.Dimension(54, 20));
        add(cbThu);
        cbThu.setBounds(690, 130, 143, 20);

        lbNgayBatDau.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbNgayBatDau.setText("Ngày bắt đầu");
        add(lbNgayBatDau);
        lbNgayBatDau.setBounds(180, 170, 120, 42);

        lbThu2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbThu2.setText("Mã nhân viên");
        add(lbThu2);
        lbThu2.setBounds(560, 120, 120, 42);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        add(jScrollPane1);
        jScrollPane1.setBounds(320, 220, 320, 50);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCaLam1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCaLam1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCaLam1ActionPerformed

    private void btnPhanCong1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPhanCong1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPhanCong1ActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnThemActionPerformed

    private void cbCalamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCalamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbCalamActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCaLam1;
    private javax.swing.JButton btnPhanCong1;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cbCalam;
    private javax.swing.JComboBox<String> cbThu;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lbGioKetThu;
    private javax.swing.JLabel lbMaca1;
    private javax.swing.JLabel lbNgayBatDau;
    private javax.swing.JLabel lbThu;
    private javax.swing.JLabel lbThu2;
    private javax.swing.JScrollPane tbCalam;
    private javax.swing.JTextField txtMaca1;
    private javax.swing.JTextField txtMaca2;
    // End of variables declaration//GEN-END:variables
}
